workspace()
#using LinearOperators
using JOLI
a=rand(3,3)+im*rand(3,3)
println(a)
vm=rand(3)+im*rand(3)
println(vm)
mvm=rand(3,2)
println(mvm)
At=joLinearFunctionT(Float64,3,3, v->a*v,v->a.'*v, v->a\v,v->a.'\v,)
Act=joLinearFunctionCT(Float64,3,3, v->a*v,v->a'*v,v->a\v,v->a'\v)
show(At)
show(Act)
show(At.')
show(Act.')
show(At')
show(Act')
show(conj(At))
show(conj(Act))
println(At*vm-a*vm)
println(Act*vm-a*vm)
println(At.'*vm-a.'*vm)
println(Act.'*vm-a.'*vm)
println(At'*vm-a'*vm)
println(Act'*vm-a'*vm)
println(conj(At)*vm-conj(a)*vm)
println(conj(Act)*vm-conj(a)*vm)
println(At\vm-a\vm)
println(Act\vm-a\vm)
println(At.'\vm-a.'\vm)
println(Act.'\vm-a.'\vm)
println(At'\vm-a'\vm)
println(Act'\vm-a'\vm)
println(conj(At)\vm-conj(a)\vm)
println(conj(Act)\vm-conj(a)\vm)
